from pydantic import BaseModel, ConfigDict, Field
from enum import Enum
from typing import Optional
from uuid import UUID
from datetime import datetime

class ReportStatusEnum(str, Enum):
    draft = "draft"
    under_review = "under_review"
    approved = "approved"
    sent = "sent"

class ReportBase(BaseModel):
    case_id: UUID
    llm_draft: Optional[str] = Field(None, description="Raw report text generated by the LLM")
    final_report: Optional[str] = Field(None, description="Final report text after reviewer edits/approval")
    pdf_path: Optional[str] = Field(None, description="Path to the generated PDF in Supabase Storage")
    status: ReportStatusEnum = ReportStatusEnum.draft

class ReportCreate(ReportBase):
    pass

class ReportUpdate(BaseModel):
    llm_draft: Optional[str] = None
    final_report: Optional[str] = None
    pdf_path: Optional[str] = None
    status: Optional[ReportStatusEnum] = None
    approved_by: Optional[UUID] = None
    approved_at: Optional[datetime] = None

class ReportResponse(ReportBase):
    id: UUID
    generated_by: UUID
    approved_by: Optional[UUID] = None
    approved_at: Optional[datetime] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)